// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/JIBA/design
// --out=$(GOPATH)/src/github.com/JIBA
// --version=v1.3.1

package app
